apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: agenda
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root
  MONGO_INITDB_DATABASE: agenda
  MONGO_INITDB_USERNAME: agenda
  MONGO_INITDB_PASSWORD: agenda
  MONGO_HOST: agenda-db-mongo
  MONGO_PORT: "27017"